baseURL = "https://trangle1302.github.io/"
languageCode = "en"
defaultContentLanguage = "en"
title = "Trang Le"
theme = "KeepIt"

paginate = 15
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""
disqusShortname = "yourdiscussshortname"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true
[menu]
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 1

  [[menu.main]]
    name = "Projects"
    url = "/projects"
    weight = 3

  [[menu.main]]
    name = "Publications"
    url = "/publications"
    weight = 4


[params]
    since = 2021
    author = "lengochaitrang@gmail.com"  # Author's name
    subtitle = "zzzzzz...."       # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "" # post or other
    dateFormatToUse = "" # set date format, default "2 January 2006"
    
    google_verification = ""
    bing_verification = ""
    yandex_verification = ""
    pinterest_verification = ""
    baidu_verification = ""

    avatar = "/images/ava1.png" #comment it to use gravatar
    socialShare = true

    description = "" # site description
    keywords = "" # site keywords

    license= 'Released under <a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

[params.gravatar]
    #email = "lengochaitrang@gmail.com"   #uncomment and insert your email address to use gravatar


[params.social]
    GitHub = "trangle1302"
    Linkedin = "trang-le-b12a6313b"
    Goodreads = "108692825-trang-le"

[params.share]
#Reddit = true
Github = true
Linkedin = true
Goodreads = true
